name: metadata

on:
  push:
  pull_request:

jobs:
  cff-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate CITATION.cff
        uses: docker://citationcff/cffconvert:latest
        with:
          args: --validate
